//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIBlazor.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIBlazor.Localization.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string ApprovalModeAsk {
            get {
                return ResourceManager.GetString("ApprovalModeAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string ApprovalModeAuto {
            get {
                return ResourceManager.GetString("ApprovalModeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string ApprovalModeDeny {
            get {
                return ResourceManager.GetString("ApprovalModeDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve required.
        /// </summary>
        public static string ApproveRequired {
            get {
                return ResourceManager.GetString("ApproveRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling tool.
        /// </summary>
        public static string CallingTool {
            get {
                return ResourceManager.GetString("CallingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files.
        /// </summary>
        public static string CategoryDeleteFiles {
            get {
                return ResourceManager.GetString("CategoryDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution.
        /// </summary>
        public static string CategoryExecution {
            get {
                return ResourceManager.GetString("CategoryExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode switch.
        /// </summary>
        public static string CategoryModeSwitch {
            get {
                return ResourceManager.GetString("CategoryModeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read files.
        /// </summary>
        public static string CategoryReadFiles {
            get {
                return ResourceManager.GetString("CategoryReadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write files.
        /// </summary>
        public static string CategoryWriteFiles {
            get {
                return ResourceManager.GetString("CategoryWriteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ConfirmQuestion {
            get {
                return ResourceManager.GetString("ConfirmQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context window.
        /// </summary>
        public static string ContextWindow {
            get {
                return ResourceManager.GetString("ContextWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Profile.
        /// </summary>
        public static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string DeleteProfileQuestion {
            get {
                return ResourceManager.GetString("DeleteProfileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Session.
        /// </summary>
        public static string DeleteSession {
            get {
                return ResourceManager.GetString("DeleteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages yet. Start a conversation!.
        /// </summary>
        public static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        public static string Endpoint {
            get {
                return ResourceManager.GetString("Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Stop. Increase the maximum output tokens..
        /// </summary>
        public static string ErrorFinishByLength {
            get {
                return ResourceManager.GetString("ErrorFinishByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models not found.
        /// </summary>
        public static string ErrorModelsNotFound {
            get {
                return ResourceManager.GetString("ErrorModelsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Plan.
        /// </summary>
        public static string ExecutePlan {
            get {
                return ResourceManager.GetString("ExecutePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra headers.
        /// </summary>
        public static string ExtraHeaders {
            get {
                return ResourceManager.GetString("ExtraHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization header with ApiKey..
        /// </summary>
        public static string ExtraHeadersIsEmpty {
            get {
                return ResourceManager.GetString("ExtraHeadersIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type @ to mention files....
        /// </summary>
        public static string InputPlaceholder {
            get {
                return ResourceManager.GetString("InputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask me to perform a task....
        /// </summary>
        public static string InputPlaceholderAgent {
            get {
                return ResourceManager.GetString("InputPlaceholderAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe your goal to create a plan....
        /// </summary>
        public static string InputPlaceholderPlan {
            get {
                return ResourceManager.GetString("InputPlaceholderPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Error Retries.
        /// </summary>
        public static string MaxRetries {
            get {
                return ResourceManager.GetString("MaxRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max output tokens.
        /// </summary>
        public static string MaxTokens {
            get {
                return ResourceManager.GetString("MaxTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete message.
        /// </summary>
        public static string MessageDelete {
            get {
                return ResourceManager.GetString("MessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit message.
        /// </summary>
        public static string MessageEdit {
            get {
                return ResourceManager.GetString("MessageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate response.
        /// </summary>
        public static string MessageRegenerate {
            get {
                return ResourceManager.GetString("MessageRegenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MCP servers configured. Click &quot;Open mcp.json&quot; to add servers..
        /// </summary>
        public static string NoMCP {
            get {
                return ResourceManager.GetString("NoMCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Rules.
        /// </summary>
        public static string OpenRules {
            get {
                return ResourceManager.GetString("OpenRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open skills folder.
        /// </summary>
        public static string OpenSkills {
            get {
                return ResourceManager.GetString("OpenSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Plan.
        /// </summary>
        public static string ProposedPlan {
            get {
                return ResourceManager.GetString("ProposedPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh tools.
        /// </summary>
        public static string RefreshTools {
            get {
                return ResourceManager.GetString("RefreshTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * When selected, the plugin will be reloaded.
        /// </summary>
        public static string ReloadAfterChange {
            get {
                return ResourceManager.GetString("ReloadAfterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry in.
        /// </summary>
        public static string RetryIn {
            get {
                return ResourceManager.GetString("RetryIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send current file.
        /// </summary>
        public static string SendCurrentFile {
            get {
                return ResourceManager.GetString("SendCurrentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send solutions stricture.
        /// </summary>
        public static string SendSolutionsStricture {
            get {
                return ResourceManager.GetString("SendSolutionsStricture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue conversation.
        /// </summary>
        public static string SessionsTitle {
            get {
                return ResourceManager.GetString("SessionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsGeneral {
            get {
                return ResourceManager.GetString("SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string SettingsTools {
            get {
                return ResourceManager.GetString("SettingsTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip SSL errors.
        /// </summary>
        public static string SkipSSL {
            get {
                return ResourceManager.GetString("SkipSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Prompt.
        /// </summary>
        public static string SystemPrompt {
            get {
                return ResourceManager.GetString("SystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking....
        /// </summary>
        public static string Thinking {
            get {
                return ResourceManager.GetString("Thinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens.
        /// </summary>
        public static string Tokens {
            get {
                return ResourceManager.GetString("Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply diff.
        /// </summary>
        public static string ToolApplyDiff {
            get {
                return ResourceManager.GetString("ToolApplyDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask user.
        /// </summary>
        public static string ToolAskUser {
            get {
                return ResourceManager.GetString("ToolAskUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build solution.
        /// </summary>
        public static string ToolBuild {
            get {
                return ResourceManager.GetString("ToolBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create file.
        /// </summary>
        public static string ToolCreateFile {
            get {
                return ResourceManager.GetString("ToolCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string ToolDeleteFile {
            get {
                return ResourceManager.GetString("ToolDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of files.
        /// </summary>
        public static string ToolDir {
            get {
                return ResourceManager.GetString("ToolDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exec.
        /// </summary>
        public static string ToolExec {
            get {
                return ResourceManager.GetString("ToolExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get errors.
        /// </summary>
        public static string ToolGetErrors {
            get {
                return ResourceManager.GetString("ToolGetErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project info.
        /// </summary>
        public static string ToolGetProjectInfo {
            get {
                return ResourceManager.GetString("ToolGetProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution structure.
        /// </summary>
        public static string ToolGetSolutionStructure {
            get {
                return ResourceManager.GetString("ToolGetSolutionStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git branches.
        /// </summary>
        public static string ToolGitBranches {
            get {
                return ResourceManager.GetString("ToolGitBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git diff.
        /// </summary>
        public static string ToolGitDiff {
            get {
                return ResourceManager.GetString("ToolGitDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git log.
        /// </summary>
        public static string ToolGitLog {
            get {
                return ResourceManager.GetString("ToolGitLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git status.
        /// </summary>
        public static string ToolGitStatus {
            get {
                return ResourceManager.GetString("ToolGitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grep search.
        /// </summary>
        public static string ToolGrepSearch {
            get {
                return ResourceManager.GetString("ToolGrepSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder in Explorer.
        /// </summary>
        public static string ToolOpenFolder {
            get {
                return ResourceManager.GetString("ToolOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read files.
        /// </summary>
        public static string ToolReadFiles {
            get {
                return ResourceManager.GetString("ToolReadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read opened file.
        /// </summary>
        public static string ToolReadOpenFile {
            get {
                return ResourceManager.GetString("ToolReadOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read skill content.
        /// </summary>
        public static string ToolReadSkillContent {
            get {
                return ResourceManager.GetString("ToolReadSkillContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timeout.
        /// </summary>
        public static string ToolRequestTimeoutSec {
            get {
                return ResourceManager.GetString("ToolRequestTimeoutSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run tests.
        /// </summary>
        public static string ToolRunTests {
            get {
                return ResourceManager.GetString("ToolRunTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search files.
        /// </summary>
        public static string ToolSearchFiles {
            get {
                return ResourceManager.GetString("ToolSearchFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch mode.
        /// </summary>
        public static string ToolSwitchMode {
            get {
                return ResourceManager.GetString("ToolSwitchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use stream.
        /// </summary>
        public static string UseStream {
            get {
                return ResourceManager.GetString("UseStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your option....
        /// </summary>
        public static string YourOption {
            get {
                return ResourceManager.GetString("YourOption", resourceCulture);
            }
        }
    }
}
