global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using Shared.Contracts;
global using UIBlazor.Agents;
global using UIBlazor.Models;
global using UIBlazor.Options;
global using UIBlazor.Utils;
global using UIBlazor.VS;