// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InvGen
{
    internal sealed partial class Vsix
    {
        public const string Id = "InvGen.a3200071-b4f2-4ba3-a720-1fb1c0267b47";
        public const string Name = "InvGen";
        public const string Description = @"Simple private LLM chat for Visual Studio";
        public const string Language = "en-US";
        public const string Version = "26.1.1";
        public const string Author = "Pavel Yakovlev";
        public const string Tags = "chatGPT, LLM, AI, OpenAI, Visual Studio";
        public const bool IsPreview = true;
    }
}
